### ISSUE TITLE
[gRIP] Error: FFI Error: Error/Cancellation/Timeout

### ISSUE THREAD

**Issue by zergcito** [gabuch2/MatterAMXX#3]
i have this problem...

> L 07/30/2023 - 01:43:20: [gRIP] Error: FFI Error: Error/Cancellation/Timeout occurred for this response.
> 
> L 07/30/2023 - 01:43:20: [AMXX] Run time error 10 (plugin "matteramxx.amxx") (native "grip_get_response_body_string") - debug not enabled!
> L 07/30/2023 - 01:43:20: [AMXX] To enable debug mode, add "debug" after the plugin name in plugins.ini (without quotes).
> [MatterAMXX] Connection failed.
> [MatterAMXX] Retrying in 3 seconds...

Cvar values:
"amx_matter_bridge_protocol" is "http"
"amx_matter_bridge_host" is "localhost"
"amx_matter_bridge_port" is "27015"

i'm using amxmodx 1.10.5467 and grip 0.1.5

**Comment by gabuch2** [comment]
Is [Matterbridge](https://github.com/42wim/matterbridge) running on the same computer?

The running Matterbridge instance must also have an API entry created on the specified port. [In the example I provided](https://github.com/gabuch2/MatterAMXX#setting-up-matteramxx) it creates an API entry in the port 1337 which it should connect into assuming the token (Set up in the cvar `amx_matter_bridge_token`) also matches.

**Comment by zergcito** [comment]
> Is [Matterbridge](https://github.com/42wim/matterbridge) running on the same computer?

Yes, its running on the same computer.

My matterbridge file:

> [discord.game]
> BindAddress="0.0.0.0:1337"
> Token="token"
> Server="ID:server"
> Buffer=1000
> 
> [[gateway]]
> name="svencoop"
> enable=true
> 
> [[gateway.inout]]
> account="discord.game"
> channel="ID:channel"

"amx_matter_bridge_token" is "token"

It still does not work, same error.

**Comment by gabuch2** [comment]
Below it's a matterbridge.toml configuration file (based directly on the one I personally use, so it should work) that should allow communication between a GoldSrc server and a Discord channel.

```toml
[general]
    IgnoreFailureOnStart=true

[discord.yourdiscordserver] #replace yourdiscordserver with whatever you want
    Token="{insert BOT TOKEN here}" # bot TOKEN, taken from https://discord.com/developers/applications, this is different from the authentication token in APIs
    Server="000000000000000000" # picked from guilds the bot is connected to. Right click your server in Discord and click Copy Server ID. Developer mode needs to be enabled.
    RemoteNickFormat="{NICK}"
    ShowEmbeds=false
    UseUserName=false
    UseDiscriminator=true
    EditDisable=true
    EditSuffix=" (edited)"
    Label="discord" #put whatever here, you can further customize the RemoteNickFormat using the {LABEL} placeholder, useful if you have many servers
    PreserveThreading=false

[api.yourgameserver] #replace yourgameserver with whatever you want
    BindAddress="0.0.0.0:4243"
    Token="{insert API TOKEN here}" # put any strong password here, value must match amx_matter_bridge_token for it to work
    Buffer=1000
    RemoteNickFormat="{NICK}"
    Label="gameserver" #put whatever here, you can further customize the RemoteNickFormat using the {LABEL} placeholder, useful if you have many servers

[[gateway]] #this section allows communication between the discord channel and the API (which MatterAMXX uses)
    name="servergateway" #put whatever, but it must be the same value as amx_matter_bridge_gateway
    enable=true #self explanatory
    [[gateway.inout]]
        account="discord.yourdiscordserver" #the discord entry, if you changed it above change it here as well
        channel="ID:1029099732565504021" #the channel where the messages will be relayed. Right click your desired channel in Discord and click Copy Server ID. Developer mode needs to be enabled.
    [[gateway.inout]]
        account="api.yourgameserver" #the api entry, if you changed it above change it here as well
        channel="api" #api entries only have an "api" channel, so leave it there
```

I probably should add this to the Readme file so people could have an easier time setting this up. 

You can further customize this entry checking out the Matterbridge documentation.
